export const GAME_CONFIG = {
  "red": { total: 151, label: "Red Version", img: "/red.jpg", api: "2" },
  "blue": { total: 151, label: "Blue Version", img: "/blue.jpg", api: "2" },
  "yellow": { total: 151, label: "Yellow Version", img: "/yellow.jpg", api: "2" },
  "gold": { total: 251, label: "Gold Version", img: "/gold.jpg", api: "3" },
  "silver": { total: 251, label: "Silver Version", img: "/silver.jpg", api: "3" },
  "crystal": { total: 251, label: "Crystal Version", img: "/crystal.jpg", api: "3" },
  "ruby": { total: 386, label: "Ruby Version", img: "/ruby.jpg", api: "4" },
  "sapphire": { total: 386, label: "Sapphire Version", img: "/sapphire.jpg", api: "4" },
  "emerald": { total: 386, label: "Emerald Version", img: "/emerald.jpg", api: "4" },
  "firered": { total: 151, label: "FireRed", img: "/fire-red.jpg", api: "2" },
  "leafgreen": { total: 151, label: "LeafGreen", img: "/leaf-green.jpg", api: "2" },
  "diamond": { total: 493, label: "Diamond", img: "/diamond.jpg", api: "5" },
  "pearl": { total: 493, label: "Pearl", img: "/pearl.jpg", api: "5" },
  "platinum": { total: 493, label: "Platinum", img: "/platinum.jpg", api: "6" },
  "heartgold": { total: 251, label: "HeartGold", img: "/heart-gold.jpg", api: "7" },
  "soulsilver": { total: 251, label: "SoulSilver", img: "/soul-silver.jpg", api: "7" },
  "black": { total: 649, label: "Black", img: "/black.jpg", api: "8" },
  "white": { total: 649, label: "White", img: "/white.jpg", api: "8" },
  "black2": { total: 649, label: "Black 2", img: "/black-two.jpg", api: "9" },
  "white2": { total: 649, label: "White 2", img: "/white-two.jpg", api: "9" },
  "x": { total: 721, label: "X", img: "/x.jpg", api: "12" },
  "y": { total: 721, label: "Y", img: "/y.jpg", api: "12" },
  "alphasapphire": { total: 721, label: "Alpha Sapphire", img: "/alpha-sapphire.jpg", api: "15" },
  "omegaruby": { total: 721, label: "Omega Ruby", img: "/omega-ruby.jpg", api: "15" },
  "sun": { total: 802, label: "Sun", img: "/sun.jpg", api: "16" },
  "moon": { total: 802, label: "Moon", img: "/moon.jpg", api: "16" },
  "ultrasun": { total: 802, label: "Ultra Sun", img: "/ultra-sun.jpg", api: "21" },
  "ultramoon": { total: 802, label: "Ultra Moon", img: "/ultra-moon.jpg", api: "21" },
  "sword": { total: 400, label: "Sword", img: "/sword.avif", api: "27" },
  "shield": { total: 400, label: "Shield", img: "/shield.jpg", api: "27" },
};